# # ### Test Clinical Chat
# # POST http://localhost:5000/api/chat
# # Content-Type: application/json

# # {
# #   "analysisId": "1234qwer",
# #   "question": "Why is this drug unsafe for the patient?"
# # }

# ### Health Check
# # GET http://localhost:5000/health

# ### Upload VCF
# POST http://localhost:5000/api/upload
# Content-Type: multipart/form-data; boundary=boundary

# --boundary
# Content-Disposition: form-data; name="vcfFile"; filename="sample.vcf"
# Content-Type: text/plain

# < ./sample.vcf
# --boundary--


### Clinical Chat
POST http://localhost:5000/api/chat
Content-Type: application/json

{
  "analysisId": "65f8a7c9d41b2a1234567890",
  "question": "Why is codeine not recommended?"
}
