# # ### Test Clinical Chat
# # POST http://localhost:5000/api/chat
# # Content-Type: application/json

# # {
# #   "analysisId": "1234qwer",
# #   "question": "Why is this drug unsafe for the patient?"
# # }

# ### Health Check
# # GET http://localhost:5000/health

# ### Upload VCF
# POST http://localhost:5000/api/upload
# Content-Type: multipart/form-data; boundary=boundary

# --boundary
# Content-Disposition: form-data; name="vcfFile"; filename="sample.vcf"
# Content-Type: text/plain

# < ./test.vcf
# --boundary--


### Clinical Chat
# POST http://localhost:5000/api/analyze/
# Content-Type: application/json

# {
#   "uploadId": "38316b24-cb0d-416d-bc62-e925c53c4cf9",
#   "drugs": "CODEINE"
# }

# Analysis ID : 699745d28fff6979b09ed0fd
## Clinical Chat Test
# POST http://localhost:5000/api/chat
# Content-Type: application/json

# {
#   "analysisId": "699745d28fff6979b09ed0fd",
#   "question": "Why is codeine not recommended for this patient?"
# }


# GET http://localhost:5000/api/results/699745d28fff6979b09ed0fd